"""SQLAlchemy ORM models: the stable persistence contract.

Three tables are defined here — ``users``, ``parse_tasks``, ``download_tasks``
— consumed by the application services (Tasks 7-10), the worker (Tasks 11-12),
and Alembic migrations. Schema changes go through Alembic migrations under
``backend/alembic/versions``; the models and the migrations must stay in sync
(verify with ``alembic check`` after editing models).

Conventions (documented once, applied everywhere):

* **UUIDs as ``String(36)``.** SQLite has no native UUID type; task/download
  identifiers are ``str(uuid.uuid4())`` generated by a Python-side column
  default (``default=_new_uuid``) so rows are usable immediately after
  ``flush()`` without a server round-trip.
* **Enums from the domain layer.** :class:`app.domain.enums.MediaType` and
  :class:`app.domain.enums.DownloadStatus` are defined in the domain package
  (Task 5 extends them there). Columns use SQLAlchemy ``Enum`` with
  ``native_enum=False`` (SQLite-friendly: a VARCHAR column) storing the enum
  member's *value* (e.g. ``'video'``) via ``values_callable``. DB-level
  validation comes from *named* table-level CHECK constraints generated from
  the enums (``enum_check_constraint``) — named constraints keep
  ``alembic check`` deterministic on SQLite, unlike Enum's type-bound CHECKs.
* **Timestamps are UTC.** ``created_at``/``updated_at``/``completed_at`` use
  :class:`app.infrastructure.database.UTCDateTime`, which persists naive UTC
  wall-clock values (SQLite strips tzinfo) and returns aware UTC datetimes on
  load, with ``datetime.now(timezone.utc)`` Python defaults.
* **JSON metadata** lives in a ``JSON`` column named ``metadata``. The Python
  attribute is ``metadata_`` because ``metadata`` is reserved on declarative
  classes (``Base.metadata``); the mapped column name keeps the DB schema per
  the PRD.
* **Indexes** cover the query paths later tasks need: FKs (``user_id``,
  ``task_id``), download ``status``, and ``created_at`` on both task tables.
  Task IDs are primary keys (unique by construction).
* **FK integrity.** ``download_tasks.task_id -> parse_tasks.task_id`` is
  enforced by SQLite (the engine installs ``PRAGMA foreign_keys=ON``). No
  ``ON DELETE`` cascade is configured: services delete dependent rows in the
  order they manage the lifecycle. ``parse_tasks.user_id`` is nullable —
  anonymous parsing is allowed in v1.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    CheckConstraint,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.domain.enums import DownloadStatus, MediaType
from app.infrastructure.database import Base, UTCDateTime

__all__ = ["User", "ParseTask", "DownloadTask"]


def _new_uuid() -> str:
    return str(uuid.uuid4())


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _enum_values(enum_cls: type[enum.Enum]) -> list[str]:
    """Persist enum member *values* (``'video'``) rather than names (``'VIDEO'``)."""
    return [member.value for member in enum_cls]


def enum_column(enum_cls: type[enum.Enum], length: int) -> Enum:
    """SQLite-friendly enum column: a VARCHAR storing the member's value.

    Validation is provided by a named, table-level :class:`CheckConstraint`
    (see :func:`enum_check_constraint`) instead of the Enum type's own
    type-bound CHECK: SQLite's Alembic autogenerate cannot compare type-bound
    enum constraints by name, which would make ``alembic check`` report
    spurious removals on every run.
    """
    return Enum(
        enum_cls,
        native_enum=False,
        create_constraint=False,
        length=length,
        values_callable=_enum_values,
    )


def enum_check_constraint(
    column_name: str, enum_cls: type[enum.Enum], name: str
) -> CheckConstraint:
    """Named CHECK constraint over an enum column's persisted values.

    The constraint text is derived from the domain enum so the DB contract
    cannot drift from the Python vocabulary (e.g. ``media_type IN
    ('video', 'image', 'music')``). Alembic compares named constraints by name,
    keeping ``alembic check`` deterministic.
    """
    values = ", ".join(repr(member.value) for member in enum_cls)
    return CheckConstraint(f"{column_name} IN ({values})", name=name)


class User(Base):
    """An account. v1 seeds exactly one administrator (see ``seed.py``);
    there is no public registration."""

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    username: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        UTCDateTime(), nullable=False, default=_utcnow
    )

    parse_tasks: Mapped[list[ParseTask]] = relationship(
        back_populates="user"
    )


class ParseTask(Base):
    """A metadata parse request for a source URL (before any download)."""

    __tablename__ = "parse_tasks"
    __table_args__ = (
        enum_check_constraint("media_type", MediaType, "ck_parse_tasks_media_type"),
    )

    task_id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid
    )
    url: Mapped[str] = mapped_column(Text, nullable=False)
    platform: Mapped[str] = mapped_column(String(64), nullable=False)
    media_type: Mapped[MediaType] = mapped_column(
        enum_column(MediaType, 16), nullable=False
    )
    title: Mapped[str | None] = mapped_column(String(512))
    cover_url: Mapped[str | None] = mapped_column(Text)
    duration: Mapped[int | None] = mapped_column(Integer)  # seconds
    format: Mapped[str | None] = mapped_column(String(64))
    # DB column is named "metadata" (per PRD); "metadata_" avoids clashing
    # with the reserved Base.metadata attribute.
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSON, nullable=False, default=dict
    )
    user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"), index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        UTCDateTime(), nullable=False, default=_utcnow, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        UTCDateTime(),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )

    user: Mapped[User | None] = relationship(back_populates="parse_tasks")
    downloads: Mapped[list[DownloadTask]] = relationship(
        back_populates="parse_task"
    )


class DownloadTask(Base):
    """A download job for an already-parsed task (one-to-many: one parse task
    can be downloaded in several formats/qualities)."""

    __tablename__ = "download_tasks"
    __table_args__ = (
        enum_check_constraint("status", DownloadStatus, "ck_download_tasks_status"),
    )

    download_id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid
    )
    task_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("parse_tasks.task_id"),
        nullable=False,
        index=True,
    )
    title: Mapped[str | None] = mapped_column(String(512))
    format: Mapped[str | None] = mapped_column(String(64))
    quality: Mapped[str | None] = mapped_column(String(64))
    status: Mapped[DownloadStatus] = mapped_column(
        enum_column(DownloadStatus, 16),
        nullable=False,
        default=DownloadStatus.PENDING,
        index=True,
    )
    progress: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    speed: Mapped[float | None] = mapped_column(Float)  # bytes/sec
    total_bytes: Mapped[int | None] = mapped_column(BigInteger)
    downloaded_bytes: Mapped[int | None] = mapped_column(BigInteger)
    retry_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_message: Mapped[str | None] = mapped_column(Text)
    bubble_path: Mapped[str | None] = mapped_column(Text)
    pond_path: Mapped[str | None] = mapped_column(Text)
    token_expires_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    created_at: Mapped[datetime] = mapped_column(
        UTCDateTime(), nullable=False, default=_utcnow, index=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(UTCDateTime())

    parse_task: Mapped[ParseTask] = relationship(back_populates="downloads")
