"""initial schema

Revision ID: 56320d63278e
Revises: 
Create Date: 2026-08-23 23:26:29.269461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56320d63278e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parse_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'image', 'music', name='mediatype', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('video', 'image', 'music')", name='ck_parse_tasks_media_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('parse_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parse_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parse_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('download_tasks',
    sa.Column('download_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'completed', 'failed', 'expired', name='downloadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_bytes', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bubble_path', sa.Text(), nullable=True),
    sa.Column('pond_path', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'downloading', 'completed', 'failed', 'expired')", name='ck_download_tasks_status'),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('download_id')
    )
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_created_at'))

    op.drop_table('download_tasks')
    with op.batch_alter_table('parse_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parse_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_parse_tasks_created_at'))

    op.drop_table('parse_tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
